In [1]:
# Importing required python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Loading the dataset
insurance_data=pd.read_csv('insurance_pre.csv')
insurance_data

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Getting the column names of insurance dataset
insurance_data.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [14]:
#Converting categorical data into numerical data
ins_data_numerical=pd.get_dummies(insurance_data,drop_first=True)
ins_data_numerical

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [15]:
#Getting the column names of insurance dataset, after converting categorical data to numerical 
ins_data_numerical.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [18]:
#Storing input and output into separate variables
indep_ins_Data=ins_data_numerical[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep_ins_data=ins_data_numerical[['charges']]

In [19]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep_ins_Data,dep_ins_data,test_size=1/3,random_state=0)

In [20]:
#Applying standardization to bring data into same scale
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [141]:
# Building SVM model using train data
from sklearn.svm import SVR
svm_regressor=SVR(kernel='rbf',C=10000)
svm_regressor=svm_regressor.fit(X_train,y_train)

C:\Users\sanja\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [142]:
#Getting count of support vectors
svm_regressor.n_support_

array([891])

In [143]:
#Getting position of support vectors
svm_regressor.support_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [144]:
#Getting values of support vectors
svm_regressor.support_vectors_

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

In [145]:
#Getting the origin/starting point
svm_regressor.intercept_

array([17332.30453654])

In [146]:
#Predicting the built model on test data
y_pred=svm_regressor.predict(X_test)
y_pred

array([10125.9192978 ,  8637.05859124, 48074.59659442, 12752.1337456 ,
        9910.96267427,  4113.6841609 ,  2218.10649964, 11307.47795818,
        7169.60974929,  5229.97724236,  7144.40781023, 10217.20681174,
        7361.54208215,  4603.52871251, 22184.76583013, 10896.15127177,
       12518.37539225,  3074.65668413,  6485.35505876, 25705.85510821,
       23211.18140367, 12754.42489468,  9993.75007331, 26298.5047289 ,
        1691.32833536,  4125.17780096,  3487.49021272,  7683.47815171,
        4145.02022049,  8376.04694042,  7735.82487084, 49167.13666912,
       13206.95173858, 10348.14832872, 15489.75086725,  3865.68863295,
        8359.74896187, 38353.12926703, 37131.83171436,  2149.28173657,
        5326.2268934 ,  3230.18662837, 21913.20626002, 49515.15921009,
       35514.11448308,  3571.11798359, 10899.87571889,  6939.07228149,
        4334.72642114, 12268.55022357,  2393.77580598,  3860.96381299,
       27168.4841069 , 45315.33458766, 12024.32824636,  2660.3278261 ,
      

In [147]:
#Calculating R^2 value
from sklearn.metrics import r2_score
svm_rsquared_value=r2_score(y_test,y_pred)
svm_rsquared_value

0.87297515322975